---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[26, 45, 15]"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "[[26], [45], [15]]"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '86'
  checked: false
name: Lista por comprensión
