---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: "{'ballena': 7, 'gallina': 7, 'platielminte': 12}"
  checked: true
- value: "{'ballena': 3, 'gallina': 3, 'platielminte': 3}"
  checked: false
- value: "{3 :  ['ballena', 'platielminte', 'gallina']}"
  checked: false
- value: "{ ['ballena', 'platielminte', 'gallina'] : 3}"
  checked: false
name: Diccionario por comprensión
