---
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "{'ballena': 7, 'gallina': 7, 'platielminte': 12}"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "{'ballena': 3, 'gallina': 3, 'platielminte': 3}"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "{3 :  ['ballena', 'platielminte', 'gallina']}"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "{ ['ballena', 'platielminte', 'gallina'] : 3}"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Devuelve error, ya que la lista no puede ser una llave.
  checked: false
name: Diccionario por comprensión
